### PR TITLE
Add custom datadog check that should track port exhaustion

### PR DESCRIPTION
**Pull request by rusty-udemy**
@udemy/sre @udemy/systems First draft of check for port exhaustion

### CODE REVIEW

**Comment by wluo** [comment]
The custom check looks ok. The comment talks about a config file (`system_ports.yaml`) though. Should that be in this PR as well?

**Comment by tripy** [comment]
Isn't the datadog standard monitor a good start?
https://docs.datadoghq.com/integrations/network/
`collect_connection_state`?

**Comment by wluo** [comment]
It doesn't look like the standard dd network monitor has anything about tcp port counts.

Also I just realized the config file will just be a datadog variable in ansible.

**Review by wluo — APPROVED** [review]
lgtm

**Comment by filipenf** [comment]
The dd monitor do collect information about connection states - essentially how many established / time wait / closing and so on so I guess we could just go with that?

**Pull request closed without merging**
